### PR TITLE
Frontend problems section animations 

### PR DESCRIPTION
**Pull request by virajchandra51**
Smoother animation on modal
Minor changes of logo and navbar with background
Animation on sponser box as discussed

### CODE REVIEW

**Comment by sahil9001** [comment]
Tab icon is not visible in deployment. Please recheck.

**Comment by virajchandra51** [comment]
@sahil9001 done

**Review by ayushgoswamiabr — APPROVED** [review]
I have reviewed the files just try to write color codes instead of color names in css from next time

**Comment by ayushgoswamiabr** [comment]
@sahil9001 please take a look

**Pull request merged**
