### PR TITLE
added section7

### PR DESCRIPTION
**Pull request by beingDeveloper2312**
Added FAQs (section 7). Sir please review.

### CODE REVIEW

**Comment by sahil9001** [comment]
Fix all `font-size` (s) and weights , use figma design to get the information about the size and weights.

**Comment by beingDeveloper2312** [comment]
Fixed the accordion issue and done the required changes. Please review.

**Comment by sahil9001** [comment]
Capture
Font weights and sizes are still incorrect please correct it. I have mentioned how to see the style in figma, refer that.

**Comment by beingDeveloper2312** [comment]
Fixed font weights and sizes. Please review.

**Comment by prakhar-asaiya** [comment]
Good work @beingDeveloper2312.

**Review by prakhar-asaiya — APPROVED** [review]

**Pull request merged**
